### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by cck7202** [SullivanNorthHS/High-school-football#7]
it wasn't the best but the letter color,placement, and how it is setup it was purty bad

**Comment by cck7202** [comment]
like really bad-(dylan nottingham)

**Comment by cck7202** [comment]
its pretty bad

**Comment by cck7202** [comment]
like not even good

**Comment by cck7202** [comment]
at all

**Comment by fatmatt52** [comment]
that violates our code of conduct kid
